"""family_transfers

Revision ID: cd557d5d7116
Revises: cfdbfafa6e96
Create Date: 2026-09-20 10:10:19.919250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd557d5d7116'
down_revision: Union[str, None] = 'cfdbfafa6e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('current_family_id', sa.Integer(), nullable=False),
    sa.Column('target_family_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('spouse_aadhaar', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['target_family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_transfer_requests_id'), 'family_transfer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_family_transfer_requests_person_id'), 'family_transfer_requests', ['person_id'], unique=False)
    op.create_index('ix_family_memberships_person_active', 'family_memberships', ['person_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_family_memberships_person_active', table_name='family_memberships', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_family_transfer_requests_person_id'), table_name='family_transfer_requests')
    op.drop_index(op.f('ix_family_transfer_requests_id'), table_name='family_transfer_requests')
    op.drop_table('family_transfer_requests')
    # ### end Alembic commands ###
