"""change_requests

Revision ID: cfdbfafa6e96
Revises: f1670e5d5fd3
Create Date: 2026-09-20 09:51:50.058231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdbfafa6e96'
down_revision: Union[str, None] = 'f1670e5d5fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('requested_value', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('supporting_document', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verification_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_family_id'), 'change_requests', ['family_id'], unique=False)
    op.create_index(op.f('ix_change_requests_id'), 'change_requests', ['id'], unique=False)
    op.create_index(op.f('ix_change_requests_person_id'), 'change_requests', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_requests_person_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_family_id'), table_name='change_requests')
    op.drop_table('change_requests')
    # ### end Alembic commands ###
