"""add_schemes

Revision ID: f1670e5d5fd3
Revises: e94c0b92977c
Create Date: 2026-09-20 09:07:46.298422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1670e5d5fd3'
down_revision: Union[str, None] = 'e94c0b92977c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'remarks',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_applications_family_id'), 'applications', ['family_id'], unique=False)
    op.create_index(op.f('ix_applications_scheme_id'), 'applications', ['scheme_id'], unique=False)
    op.add_column('scheme_rules', sa.Column('description', sa.String(), nullable=False))
    op.add_column('scheme_rules', sa.Column('target', sa.String(), nullable=False))
    op.add_column('scheme_rules', sa.Column('rule_config', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_scheme_rules_scheme_id'), 'scheme_rules', ['scheme_id'], unique=False)
    op.drop_column('scheme_rules', 'operator')
    op.drop_column('scheme_rules', 'logical_group')
    op.drop_column('scheme_rules', 'field_name')
    op.drop_column('scheme_rules', 'value')
    op.alter_column('schemes', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_unique_constraint(None, 'schemes', ['name'])
    op.drop_column('schemes', 'created_at')
    op.drop_column('schemes', 'benefit_description')
    op.drop_column('schemes', 'department')
    op.drop_column('schemes', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('schemes', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('schemes', sa.Column('benefit_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('schemes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schemes', type_='unique')
    op.alter_column('schemes', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.add_column('scheme_rules', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scheme_rules', sa.Column('field_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scheme_rules', sa.Column('logical_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scheme_rules', sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scheme_rules_scheme_id'), table_name='scheme_rules')
    op.drop_column('scheme_rules', 'rule_config')
    op.drop_column('scheme_rules', 'target')
    op.drop_column('scheme_rules', 'description')
    op.drop_index(op.f('ix_applications_scheme_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_family_id'), table_name='applications')
    op.alter_column('applications', 'remarks',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
